pv_garage:
  type: PVForecast
  kwPeak: 5
  direction: south-west
  latitude: 30
  longitude: 50

batterie_keller:
  type: Battery
  capacity: 10

wohnung:
  type: HouseholdLoad
  average_consumption: 80
